name: pint
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Pint
        uses: prymitive/pint-action@v1
        with:
          token: ${{ github.token }}
          workdir: "alerts"
          loglevel: debug
          minSeverity: info

